const COLORS = {
    BLACK: "black",
    ALMOST_BLACK: "almost_black",
    GREY: "grey",
    LIGHT_GREY: "light_grey",
    WHITE: "white",
    LIGHT_PURPLE: "light_purple",
    PURPLE: "purple",
    DARK_PURPLE: "dark_purple",
    LIGHT_BLUE: "light_blue",
    BLUE: "blue",
    DARK_BLUE: "dark_blue",
    LIGHT_GREEN: "light_green",
    GREEN: "green",
    DARK_GREEN: "dark_green",
    LIGHT_YELLOW: "light_yellow",
    YELLOW: "yellow",
    LIGHT_ORANGE: "light_orange",
    ORANGE: "orange",
    DARK_ORANGE: "dark_orange",
    LIGHT_RED: "light_red",
    RED: "red",
    DARK_RED: "dark_red",
    PINK: "pink",
    BROWN: "brown",
    AQUA: "aqua",
    MAGENTA: "magenta",
    CYAN: "cyan",
};
export default COLORS;
