// HELP
import padStringToLength79 from "../util/padStringToLength79.js";
// Arrays of help messages for the HELP command
const HELP = {
    AFFIX: [
        `This feature is still in development.`,
        `${padStringToLength79(`Affix`)}`,
        `An affix boosts a stat on a mob, item, or target of a spell. The effect of each stat is explained in a help file (e.g. HELP DEXTERITY). An item can have 0-3 affixes, and a mob can have 0-5. It's okay to have no affixes, or more than one affix on the same stat, e.g. for a double or triple boost to dexterity on the same boots, or a minotaur that is extra, extra, extra strong.`,
    ],
    AGGRESSIVE_MOB: [
        `${padStringToLength79(`Aggressive Mob`)}`,
        `This feature is still in development. When implemented, An aggressive mob will attack users without being provoked.`,
    ],
    ARMOR: [
        `${padStringToLength79(`Armor`)}`,
        `An armor item may fit on one location, or have multiple options. (e.g. a long, golden chain might fit around the neck or around the waist)`,
    ],
    AUTHOR: [
        `${padStringToLength79(`Author, Character, User`)}`,
        `The words author, character, and user all refer to the same thing: a human person who plays Restoria. Everyone in the game is an author in the sense that they can CREATE zones and their contents. We are all users and characters in the sense that we interact with the world of zones created by other authors, often in a role-playing style of gameplay. A person may have multiple user accounts representing different characters. That's why "user", "character", and "author" are used interchangeably in Restoria.`,
    ],
    AUTOEXAMINE: [
        `${padStringToLength79(`Autoexamine`)}`,
        `While LOOK descriptions are short (<80 characters), and EXAMINE descriptions are longer (<240 characters), some users prefer to only see one or the other when they enter a room. You can type AUTOEXAMINE OFF if you prefer to only see short descriptions when entering a room, or AUTOEXAMINE ON to see longer ones. You can also type AUTOEXAMINE on its own to toggle the setting.`,
        `<span style="color:var(--green)">See also HELP DESCRIPTION.</span>`,
    ],
    BUG: [
        `Restoria's first beta was coded and written by Ralu (aka Mark Wells), so of course it is full of dumb bugs. If you find one, type BUG to report it, and include lots of details about what happened, and what you were doing when it happened (e.g. the last commands you tried to use, the buggy result, what you were expecting, etc). The game will automatically record your username, the date & time, and your location in the game when you submit the report, so please try to report from the time and place you observed the bug. If you can't, then include those details in your description too, please. You can type BUGS to see a "todo" list of bugfixes Ralu is working on.`,
    ],
    CHEATSHEET: [
        `${padStringToLength79(`HELP CHEATSHEET`)}`,
        `Restoria is made of user-created story environments called <span style="color:var(--white)">zones</span>. Each zone contains interactive <span style="color:var(--orange)">rooms</span>, <span style="color:var(--blue_light)">items</span>, and <span style="color:var(--green_light)">mobs</span> (aka creatures and npcs).`,
        `After you log in, try typing a <span style="color:var(--green)">COMMAND</span> in the box at the bottom:`,
        `<span style="color:var(--yellow)">To explore</span>, <span style="color:var(--green)">LOOK</span> at the <span style="color:var(--orange)">room</span>, <span style="color:var(--blue_light)">items</span>, and <span style="color:var(--green_light)">mobs</span> in the <span style="color:var(--orange)">room</span> with you. Check the <span style="color:var(--green)">EXITS</span> to see where you can go</span>, and move <span style="color:var(--green)">NORTH</span>, <span style="color:var(--green)">EAST</span>, <span style="color:var(--green)">SOUTH</span>, <span style="color:var(--green)">WEST</span>, <span style="color:var(--green)">UP</span>, <span style="color:var(--green)">DOWN</span> to visit different <span style="color:var(--orange)">rooms</span>. <span style="color:var(--green)">GET</span>, <span style="color:var(--green)">DROP</span>, or <span style="color:var(--green)">GIVE</span> <span style="color:var(--blue_light)">items</span>, <span style="color:var(--green)">PUT</span> them into container <span style="color:var(--blue_light)">items</span>, and <span style="color:var(--green)">WEAR</span> equipment <span style="color:var(--blue_light)">items</span>. If you get lost, <span style="color:var(--green)">RECALL</span> to warp back to "The Snails", the centre of Restoria Town.`,
        `<span style="color:var(--yellow)">To communicate with other players,</span> <span style="color:var(--green)">SAY</span> something to the <span style="color:var(--orange)">room</span> you're in, <span style="color:var(--green)">SHOUT</span> it to everyone nearby, or <span style="color:var(--green)">TELEPATH</span> a message to a single user.`,
        `<span style="color:var(--yellow)">To author new parts of the game</span>, try <span style="color:var(--green)">CREATE ZONE</span> to build your own story environment outside Restoria City, then <span style="color:var(--green)">GOTO</span> that area and start to <span style="color:var(--green)">CREATE</span> your own <span style="color:var(--orange)">rooms</span>, <span style="color:var(--blue_light)">items</span>, and <span style="color:var(--green_light)">mobs</span>. <span style="color:var(--green)">EDIT</span> the descriptions and details of things you've created, or <span style="color:var(--green)">ERASE</span> them. Choose an <span style="color:var(--green)">EDITOR</span> for your zone, and they can <span style="color:var(--green)">SUGGEST</span> ways to improve it.`,
        `<span style="color:var(--yellow)">To learn more about playing Restoria,</span> read the <span style="color:var(--green)">HELP</span> files (e.g. <span style="color:var(--green)">HELP CREATE</span> to learn more about creating things in the game).`,
        `Enter <span style="color:var(--green)">HELP CHEATSHEET</span> in-game to see this again.`,
    ],
    CONTAINER: [
        `${padStringToLength79(`CONTAINER, CAPACITY`)}`,
        `A container is an item that can hold other (non-container) items inside. A container's capacity is the maximum items it can store (10, by default).`,
    ],
    CREATE: [
        `${padStringToLength79(`CREATE`)}`,
        `You are an author in Restoria, and authors can CREATE ZONE, CREATE ITEM, CREATE MOB, CREATE ROOM, and CREATE EXIT to add things to zones they own. For rooms and exits, you need to provide a direction (e.g. CREATE ROOM N). The other options each open a form to enter your writing, and the HELP for each form will display automatically when it opens.`,
    ],
    CREATE_EXIT: [
        `${padStringToLength79(`CREATE EXIT`)}`,
        `Open an exit between this room and an adjacent room. This is only possible if there's a room in the direction you specify. E.g. ""CREATE EXIT NORTH" will only work if there's already a room to the North.`,
    ],
    CREATE_ITEM: [
        `${padStringToLength79(`CREATE ITEM`)}`,
        `<span style="color:var(--red)">Name:</span> e.g '<span style="color: var(--blue_light)">a green potion</span>' or '<span style="color: var(--blue_light)">Excaliburr the Frozen'</span>`,
        `<span style="color:var(--red)">Keywords:</span> e.g 'potion, green' or 'sword, Excaliburr, Frozen'`,
        `<span style="color:var(--red)">Type:</span> gives an item certain behaviours`,
        `<span style="color:var(--red)">MinLvl:</span> player must be at least this level to use or equip it`,
        `<span style="color:var(--red)">Price:</span> costs to purchase (selling price will be less)`,
        `<span style="color:var(--red)">Container:</span> this item may spawn or hold other items inside`,
        `<span style="color:var(--red)">Look:</span> how the player sees the item when they look or enter a room`,
        `<span style="color:var(--red)">Examine:</span> a paragraph a player seens when they examine the item`,
        `<span style="color:var(--green)">See also HELP AUTOEXAMINE.</span>`,
    ],
    CREATE_MOB: [
        `${padStringToLength79(`CREATE MOB`)}`,
        `A Mob is a monster, creature, or non-player character in a zone. "MOB" stands for "Mobile Object", which is an old gaming term to refer to anything in a game that might move around or act on its own.`,
        `<span style="color:var(--red)">Name:</span> e.g '<span style="color: var(--green_light)">a green goblin</span>' or '<span style="color: var(--green_light)">Greg the blacksmith'</span>`,
        `<span style="color:var(--red)">Keywords:</span> e.g 'goblin, green' or 'blacksmith, Greg'`,
        `<span style="color:var(--red)">Pronouns:</span> may appear in place of a name ("Greg eats." vs "<u>He</u> eats.")`,
        `<span style="color:var(--red)">Level:</span> determines its stats and learned spells and abilities`,
        `<span style="color:var(--red)">Job:</span> determines abilities and combat style`,
        `<span style="color:var(--red)">Look:</span> how the player sees the mob when they look or enter a room`,
        `<span style="color:var(--red)">Examine:</span> a paragraph a player sees when they examine the mob`,
        `<span style="color:var(--green)">See also HELP AUTOEXAMINE.</span>`,
    ],
    CREATE_ROOM: [
        `${padStringToLength79(`CREATE ROOM`)}`,
        `A Room is a specific area of a zone, and there should be many rooms in a zone. Despite being called "Room", a Room can be any specific location, even an outdoor area without walls. Examples of rooms could be "A Walkway in the Garden", "The Smallest Dungeon Cell", or "Persephone's Walk-In Closet". If a Zone is a large area where many parts of a story can happen, a Room is a specific place where a specific event (e.g. a conversation, a battle) can happen.`,
        `e.g. CREATE ROOM NORTH will create a room to the North. You can add the name of the room, if you know it already (e.g. CREATE ROOM NORTH A Peaceful Meadow)`,
    ],
    CREATE_ZONE: [
        `${padStringToLength79(`CREATE ZONE, EDIT ZONE`)}`,
        `A Zone is a broad area in the game; think of it as a setting where many parts of a story can take place. A zone is made up of smaller places called Rooms. For example, "Restoria City" is a zone, and "The Snails" is a room within that zone. Other examples of a zone may be "The Haunted Unicorn Forest", "Bunnyland", or "Drake's Vampiric Castle", whereas examples of rooms inside those zones could be "A Mossy Glade", "The Bunny Cafeteria", or "Drake's Treasure Chamber".`,
        `<span style="color:var(--red)">Name:</span> the zone's title, e.g. "The Mushroom City"`,
        `<span style="color:var(--red)">Respawn:</span> how many minutes before the whole zone's mobs, doors, & items respawn`,
        `<span style="color:var(--red)">Look:</span> a sentence shown to a player when they survey the wilderness nearby`,
        `e.g. "Clouds of spores and odd, fungal shapes protrude from the horizon."`,
        `<span style="color:var(--red)">Examine:</span> a paragraph a player sees when they examine the zone`,
        `<span style="color:var(--green)">See also HELP AUTOEXAMINE.</span>`,
        `<span style="color:var(--red)">Study:</span> a player learns some more details when they study the zone`,
        `<span style="color:var(--red)">Research:</span> the full history of the zone, in paragraphs`,
        `A good research text rewards the reader with some secrets about the zone.`,
    ],
    DESCRIPTION: [
        `${padStringToLength79(`DESCRIPTION, LOOK, EXAMINE, STUDY, RESEARCH`)}`,
        `<span style="color:var(--red)">Look:</span> A 'look' description should fit on one line (80 characters or less). It is a full sentence, and a reader's first impression of the item, mob, user, room, or zone it describes. The 'look' descriptions of everything obvious in a room are shown automatically to a player when they enter it, and when they use the LOOK command on its own. Users can't change their own 'look' descriptions.`,
        `<span style="color:var(--green)">See also HELP LOOK COMMAND.</span>`,
        `<span style="color:var(--red)">Examine:</span> When a reader uses the EXAMINE command on an item, mob, or user, this short paragraph (240 characters or less) is what they see. For a room, the 'examine' will appear automatically if they have AUTOEXAMINE ON.`,
        `<span style="color:var(--green)">See also HELP AUTOEXAMINE.</span>`,
        `<span style="color:var(--red)">Study:</span> When a reader uses the STUDY command on an item, mob, user, room, or zone, this long description (640 characters or less) is what they see. It should include rich detail that a reader wouldn't notice at first glance, and may even share secrets to reward those careful and patient readers who take the time to STUDY.`,
        `<span style="color:var(--red)">Research:</span> When a reader uses the RESEARCH command on an item, mob, user, room, or zone, this complete story (1600 characters or less) is shown to them. Good authors will use the 'research' description to tell some history. They may explain why certain things in their zone are they way they are. This is also a fun place to include easter eggs or major secrets about your zone, since only the best and most deserving readers explore with the RESEARCH command.`,
    ],
    DROP: [
        `${padStringToLength79(`DROP`)}`,
        `Sometimes you want to get rid of an item. You can DROP it on the ground in most place (e.g. DROP APPLE). You can use an ordinal if you want to drop the second apple in your inventory (e.g. DROP 2.APPLE), or all items matching a keyword (e.g. DROP ALL.POTION).`,
    ],
    EDIT: [
        `${padStringToLength79(`EDIT`)}`,
        `You can EDIT most things in a zone you created. EDIT ZONE, EDIT ROOM, EDIT MAP, EDIT ITEM, EDIT MOB, and even EDIT USER are ways to change various details of the things you write in Restoria.`,
    ],
    EDIT_ITEM: [
        `${padStringToLength79(`EDIT ITEM`)}`,
        `<span style="color:var(--red)">Name:</span> e.g '<span style="color: var(--blue_light)">a green potion</span>' or '<span style="color: var(--blue_light)">Excaliburr the Frozen'</span>`,
        `<span style="color:var(--red)">Keywords:</span> e.g 'potion, green' or 'sword, Excaliburr, Frozen'`,
        `<span style="color:var(--red)">Price:</span> the cost to purchase (selling price will be less)`,
        `<span style="color:var(--red)">MinLvl:</span> a player must be at least this level to use or equip it`,
        `<span style="color:var(--red)">Type:</span> gives an item certain behaviours`,
        `<span style="color:var(--red)">Container:</span> this item may spawn or hold other items inside`,
        `<span style="color:var(--red)">Capacity:</span> determines how many items it can hold.`,
    ],
    EDIT_MAP: [
        `${padStringToLength79(`EDIT MAP`)}`,
        `For now this lets you change the character and color of a room's tile on the map. In the future, we'd like to improve this feature, so you could edit the whole map for a floor at once, without having to move around to each room.`,
    ],
    EDIT_MOB: [
        `${padStringToLength79(`EDIT MOB`)}`,
        `<span style="color:var(--red)">Name:</span> e.g '<span style="color: var(--green_light)">a green goblin</span>' or '<span style="color: var(--green_light)">Greg the blacksmith'</span>`,
        `<span style="color:var(--red)">Keywords:</span> e.g 'goblin, green' or 'blacksmith, Greg'`,
        `<span style="color:var(--red)">Pronouns:</span> may appear in place of a name ("Greg eats." vs "<u>He</u> eats.")`,
        `<span style="color:var(--red)">Level:</span> determines its stats and learned spells and abilities`,
        `<span style="color:var(--red)">Job:</span> determines abilities and combat style`,
        `<span style="color:var(--red)">Spirit:</span> negative is a moon spirit, 0 is neutral, positive is a sun spirit`,
        `<span style="color:var(--green)">See also HELP UNIQUE, HELP MOUNT, HELP AGGRESSIVE</span>`,
    ],
    EDIT_ROOM: [
        `${padStringToLength79(`EDIT ROOM Description`)}`,
        `<span style="color:var(--red)">Name:</span> e.g '<span style="color: var(--yellow_light)">A Long Hallway</span>' or '<span style="color: var(--yellow_light)">The Potion Shoppe'</span>`,
        `<span style="color:var(--red)">Look:</span> a very short description of the room (shown automatically with AUTOEXAMINE OFF)`,
        `<span style="color:var(--red)">Examine:</span> a paragraph a player sees when they look or enter the room (with AUTOEXAMINE ON)`,
        `<span style="color:var(--green)">See also HELP AUTOEXAMINE.</span>`,
        `<span style="color:var(--red)">Study:</span> a player learns some history when they study the room`,
        `<span style="color:var(--red)">Research:</span> tells the full history of the room, in paragraphs`,
        `A good research text rewards the reader with some secrets about the room. Read HELP DESCRIPTION for more.`,
    ],
    EDIT_ROOM_TAGS: [
        `${padStringToLength79(`EDIT ROOM Tags`)}`,
        `<span style="color:var(--red)">Dark:</span> items, mobs, and players are hidden unless a lamp is present`,
        `<span style="color:var(--red)">Indoors:</span> weather won't take effect here`,
        `<span style="color:var(--red)">On Water:</span> players and mobs can't enter without levitate`,
        `<span style="color:var(--red)">Underwater:</span> players will take drowning damage without magic`,
        `<span style="color:var(--red)">No Mounts:</span> no one can enter this room while mounted`,
        `<span style="color:var(--red)">No Mobs:</span> mobs can't enter this room`,
        `<span style="color:var(--red)">No Magic:</span> no one can cast spells in this room`,
        `<span style="color:var(--red)">No Combat:</span> no one can enter combat in this room`,
        `<span style="color:var(--red)">Cap:</span>how many players/mobs can fit inside before more are blocked from entering`,
    ],
    EDITOR: [
        `${padStringToLength79(`EDITOR`)}`,
        `The EDITOR command designates another user to be your zone editor (e.g. EDITOR RALU). The person you choose can enter your unpublished zones and read all your content. They can also use the SUGGEST command to give you notes to improve your zone. If you want to remove your editor without replacing them, type EDITOR NONE.`,
    ],
    ERASE: [
        `${padStringToLength79(`ERASE, DELETE, ERASE ITEM, ERASE MOB, ERASE ROOM, ERASE USER, ERASE ZONE`)}`,
        `Use the ERASE or DELETE command to ERASE ITEM, ERASE MOB, or ERASE ROOM in your zone. To erase a user, contact Ralu or another game administrator. Except in special circumstances, we'll only erase one of your users per month. You can't erase a zone; edit or erase its contents instead.`,
        `Remember, <span style="color:var(--red)">ERASE cannot be undone!</span> We recommend saving all your writing somewhere, (e.g. Google Drive), so you have a back-up copy of your hard work. Wise authors do all their writing in another doc, then copy/paste into Restoria. Why not back up your writing before you ERASE, just in case?`,
    ],
    ERASE_EXIT: [
        `${padStringToLength79(`ERASE EXIT`)}`,
        `Remove an exit between this room and an adjacent room (e.g. ERASE ROOM NORTH). Erasing an exit can make some rooms in your zone inaccessible. You can use GOTO, then CREATE EXIT or CREATE ROOM to reconnect them.`,
    ],
    EXITS: [
        `${padStringToLength79(`EXITS, EDIT ROOM Exits`)}`,
        `The EXITS command shows a user where they can go from their current location.`,
        `Exits allow users and mobs to move between rooms in a zone. An exit will always spawn closed and locked if a key is assigned to it.`,
        `<span style="color:var(--red)">Key:</span> someone can unlock the exit if this item is in their inventory`,
        `<span style="color:var(--red)">Hidden:</span> exit can't be seen or used, except by those who successfully SEARCH`,
        `<span style="color:var(--red)">Closed:</span> closed by default when the zone is spawned`,
    ],
    GET: [
        `${padStringToLength79(`GET`)}`,
        `You can GET items from the ground (e.g. GET APPLE) or a container (e.g. GET APPLE BAG). You can use an ordinal (e.g. to get the second apple, GET 2.APPLE, or from the second chest GET APPLE 2.CHEST). You can use ALL to get everything with a given keyword (e.g. GET ALL.POTION). You can't select ALL containers.`,
    ],
    GIVE: [
        `${padStringToLength79(`GIVE`)}`,
        `If there's room in their inventory, you can GIVE an item to a player or mob (e.g. GIVE APPLE RALU). You can use an ordinal (e.g. to give the second apple, GIVE 2.APPLE RALU, or to the second goblin GIVE APPLE 2.GOBLIN). To avoid spammy giving, you can only give one item at a time.`,
    ],
    GOTO: [
        `${padStringToLength79(`GOTO`)}`,
        `Warp to any room in any unpublished zone you created. If another author chose you as their EDITOR, that person's zones will be on your GOTO list as well.`,
    ],
    HIDDEN: [
        `This feature is still in development.`,
        `${padStringToLength79(`HIDDEN_ITEM, HIDDEN_USER, HIDDEN_MOB, HIDDEN_EXIT`)}`,
        `Hidden things don't show up normally on LOOK. Some will appear after a SEARCH, and some may only be detected with certain magic.`,
    ],
    INVENTORY: [
        `${padStringToLength79(`INVENTORY`)}`,
        `Type INVENTORY or I to see all the items you're carrying. To see inside your containers, use LOOK (e.g. LOOK BAG).`,
    ],
    ITEM_NODE: [
        `${padStringToLength79(`Item Node`)}`,
        `Item nodes help a zone load its items. Each item node spawns its item into a container, mob inventory, or room when the zone is loaded. Choose an item and click <span style="color:var(--green)">add</span> to create an item node for it. Click <span style="color:var(--red)">remove</span> next to an existing node to remove it. These changes won't be saved until you submit the form.`,
    ],
    ITEM_SPELL_PROPERTIES: [
        `${padStringToLength79(`Item Spell Properties`)}`,
        `Each spell has a help file describing its effects (e.g. HELP BLESS)`,
        `<span style="color:var(--red)">Level:</span> higher can mean stronger effect, more damage, longer duration, etc.`,
        `<span style="color:var(--red)">Charges:</span> how many times the item can be used before it disappears`,
    ],
    ITEM_TYPE: [
        `This feature is still in development.`,
        `${padStringToLength79(`Item Type, Armor, Potion, Scroll, Token, Treasure, Wand, Weapon, Fishing Rod`)}`,
        `An item's type determines how that item can be used.`,
        `<span style="color:var(--red)">Armor:</span> can be worn to boost stats on a user or mob`,
        `<span style="color:var(--red)">Gold:</span> increases your gold (then disappears) when it enters your inventory`,
        `<span style="color:var(--red)">Key:</span> follows specific behaviours for keys`,
        `<span style="color:var(--red)">None:</span> has no special traits, and just enhances the style of the zone`,
        `<span style="color:var(--red)">Potion:</span> you can DRINK a potion to consume it and cast its spell on yourself`,
        `<span style="color:var(--red)">Scroll:</span> RECITE a scroll to consume it and cast its spell on your target`,
        `<span style="color:var(--red)">Token:</span> some quests and competitions ask you to collect certain token items`,
        `<span style="color:var(--red)">Treasure:</span> sells at a high price, and has no other use`,
        `<span style="color:var(--red)">Wand:</span> USE a wand to cast its spell on your target. When out of charges, it disappears`,
        `<span style="color:var(--red)">Weapon:</span> type WIELD to equip a weapon for combat`,
        `<span style="color:var(--red)">Fishing Rod:</span> USE it to go fishing!`,
    ],
    ITEM_TAG: [
        `${padStringToLength79(`Item Tag, Fixture, Food, Lamp, Temporary`)}`,
        `<span style="color:var(--red)">Cleric:</span> clerics can use or equip it`,
        `<span style="color:var(--red)">Mage:</span> mages can use or equip it`,
        `<span style="color:var(--red)">Rogue:</span> rogues can use or equip it`,
        `<span style="color:var(--red)">Warrior:</span> warriors can use or equip it`,
        `<span style="color:var(--red)">Moon:</span> players with moon-aligned spirit (<=-333) can use or equip it`,
        `<span style="color:var(--red)">Neutral:</span>players with a neutral spirit (-333 to 333) can use or equip it`,
        `<span style="color:var(--red)">Sun:</span> players with a sun-aligned spirit (>=333) can use or equip it`,
        `<span style="color:var(--red)">Food:</span> can be eaten and may hold a spell`,
        `<span style="color:var(--red)">Lamp:</span> illuminates a dark room, revealing players, mobs, and items`,
        `<span style="color:var(--red)">Hidden:</span> not normally visible until you search`,
        `<span style="color:var(--red)">Fixture:</span> can't be taken or moved (e.g. a large wardrobe)`,
        `<span style="color:var(--red)">Quest:</span> needed for a quest`,
        `<span style="color:var(--red)">Temporary:</span> automatically erased from inventory when you log out`,
        `<span style="color:var(--red)">Container:</span> can spawn and hold other items inside`,
    ],
    JOB: [
        `This feature is still in development.`,
        `${padStringToLength79(`Job`)}`,
        `A job defines the abilities available to a character or mob at their level.`,
        `<span style="color:var(--red)">Cleric:</span> learns spells for healing and protection, and some for damaging foes`,
        `<span style="color:var(--red)">Mage:</span> learns spells for damaging foes, and some utility spells`,
        `<span style="color:var(--red)">Rogue:</span> sneaks, steals, and backstabs foes for big damage`,
        `<span style="color:var(--red)">Warrior:</span> hits hard, blocks foes, and soaks up damage`,
    ],
    KEYWORDS: [
        `${padStringToLength79(`Keywords`)}`,
        `Keywords are single words that help users target something (an item, mob, etc.). Each keyword should also appear somewhere in the item or mob's description, and if it has a proper name (e.g. Greg), that name must be one of the keywords. For example, if a mob's 'look' description is "Greg the white kitten purrs gently in the corner." that mob's keywords might be "Greg, kitten, white". That way, a player could type "pet Greg", "pet kitten", or "pet white" to target him.`,
    ],
    LIGHT: [
        `${padStringToLength79(`LIGHT`)}`,
        `LIGHT can be an ambiguous word. In Restoria, a LIGHT weapon can be thrown or dualwielded. An item that can illuminate a dark room is a LAMP.`,
    ],
    LOOK_COMMAND: [
        `${padStringToLength79(`LOOK COMMAND`)}`,
        `Use LOOK on its own to see the contents of the room you're in. You can also LOOK at or in something (e.g. LOOK APPLE, LOOK CHEST). You can use an ordinal (e.g. to look at the second apple, LOOK 2.APPLE, or in the second chest LOOK APPLE 2.CHEST).`,
    ],
    MAP: [
        `This feature is still in development.`,
        `${padStringToLength79(`MAP`)}`,
        `Each square on your MAP shows a room near you, with your position at the center. Dotted lines show closed doors, and solid lines are walls (or hidden exits). By default, you should see a map every time you change location, or when you type MAP. Type MAP OFF or MAP ON to toggle this feature. MAP 6 will change the radius of your map display to 6 rooms away.`,
    ],
    MOB: [
        `This feature is still in development.`,
        `${padStringToLength79(`MOB, MONSTER, NPC`)}`,
        `Mob stands for "Mobile Object" (an old gaming term for anything that moves around in a game, usually a monster or NPC). The first games with mobs appeared in the late 1970's. Type CREATE MOB in your zone to bring it to life; give your readers monsters, peaceful creatures, and NPCs to interact with and even battle. A mob can have useful information, a quest, and equipment and treasure for a user to win, buy, or loot.`,
    ],
    MOB_NODE: [
        `${padStringToLength79(`Mob Node`)}`,
        `A mob node spawns a specific mob into the room when the zone is loaded. On the EDIT ROOM form, Choose a mob and click <span style="color:var(--green)">add</span> to create an mob node for it. Click <span style="color:var(--red)">remove</span> next to an existing node to remove it. These changes won't be saved until you click "Update Room".`,
    ],
    MOUNT: [
        `This feature is still in development.`,
        `${padStringToLength79(`MOUNT`)}`,
        `A mount is a mob that a user can ride around, usually increasing their speed and movement capacity outdoors. Use the MOUNT command to (for example) MOUNT HORSE before a long journey.`,
    ],
    MOVE: [
        `${padStringToLength79(`Move`)}`,
        `There is no MOVE command. Instead, type the direction you want to move:`,
        `NORTH, EAST, SOUTH, WEST, UP, or DOWN.`,
    ],
    NAME: [
        `${padStringToLength79(`Name`)}`,
        `In Restoria, a 'name' is a phrase (not a single word or a full sentence) that shows in interactions with a user, item, or mob. For example, the name "Greg, the Blacksmith" will show up when you hug that mob ("You hug Greg, the Blacksmith."), or enter combat with him ("Greg, the Blacksmith swings his hammer at you!"). The name of a room is displayed before its description when you enter or LOOK at it, and also on the list of exits in its neighbouring rooms. Some examples of names:`,
        `Items: "a blue potion", "Sting, the silver dagger", "a leather hat"`,
        `Mobs: "a goblin", "the gate guard", "Silvia, the white mage"`,
        `Rooms: "a shady garden", "the castle kitchen", "Bernie's Burger Shack"`,
    ],
    PASSWORD: [
        `${padStringToLength79(`PASSWORD`)}`,
        `To change your password, type PASSWORD and your new pasword twice.`,
        `E.g. to change your password to waTerm3lon, you would type:`,
        `PASSWORD waTerm3lon waTerm3lon`,
        `Your new password must be at least 8 characters long and include lowercase, uppercase, and a number.`,
    ],
    PRONOUNS: [
        `${padStringToLength79(`Pronouns`)}`,
        `A pronoun is a part of speech we use in place of a noun or name, usually to avoid constant repetition of the name. For example, instead of saying "Greg, the Blacksmith brushes Greg, the Blacksmith's teeth before Greg, the Blacksmith goes to bed," we can say "Greg brushes HIS teeth before HE goes to bed." "It" and "They" are also pronouns. We can use "it" as a pronoun for things that have no gender (e.g. "It looks valuable."), and "they" for someone whose gender we don't know (e.g. "Someone left their sweater here. I hope they come back to find it.").`,
    ],
    PUT: [
        `${padStringToLength79(`QUIT`)}`,
        `If an item is a container and has room, you can PUT other items inside (e.g. PUT APPLE BAG). You can use an ordinal (e.g. to put the second apple in the bag, PUT 2.APPLE BAG, or to put the apple in the second bag PUT APPLE 2.BAG). You can use ALL to put everything with a given keyword inside (e.g. PUT ALL.POTION BAG).`,
    ],
    QUIT: [
        `${padStringToLength79(`QUIT`)}`,
        `Use the QUIT command to leave the game and return your character to world recall, The Snails statue in Restoria City.`,
    ],
    RECALL: [
        `${padStringToLength79(`RECALL`)}`,
        `User the RECALL command to return to safety at The Snails statue, the centre of Restoria City.`,
    ],
    RULES: [
        `${padStringToLength79(`RULES`)}`,
        `We protect the safety, dignity, and fun of Restoria users by removing players who abuse others. Everything we say and do in Restoria is logged, and if you intentionally bother anyone else in the game, your account may be deleted without warning. In this case, your writing, character experience, equipment & items, and everything else associated with your account would be permanently removed (another good reason why wise authors keep a backup of all their writingf). If you don't have good intentions towards all other players at all times, stop playing Restoria until you do.`,
    ],
    SAVE: [
        `${padStringToLength79(`SAVE`)}`,
        `When you make a change in your zone (as an author, e.g. EDIT MOB) it is saved automatically.`,
        `Saving your character works differently: the SAVE command manually saves your (non-zone) character data like location, inventory, equipment, etc. The game tries to do this for you automatically (e.g. when you make a change with AUTOEXAMINE, EDIT USER, EDITOR, MAP, PASSWORD, or GET an item, etc.).`,
        `<span style="color:var(--red)">REMEMBER, HOWEVER:</span>`,
        `To protect our database, Restoria won't SAVE your character (manually or automatically) more than once every 10 seconds.`,
    ],
    SAY: [
        `${padStringToLength79(`SAY`)}`,
        `User the SAY command to communicate with users in the same room.`,
    ],
    SHOUT: [
        `${padStringToLength79(`SHOUT`)}`,
        `User the SHOUT command to communicate with users in the same zone.`,
    ],
    SPELL: [
        `This feature is still in development.`,
        `${padStringToLength79(`Spell`)}`,
        `A magic spell has a damaging, healing, or some other effect on its target. Users and mobs learn spells if they belong to the mage or cleric jobs. Certain items like scrolls, potions, and wands carry spells that any user can cast by using the item. Many spells have a duration, after which the spell and its effects disappear. It is said amongst the wise that the creation of all Restoria began with a single spell.`,
    ],
    STATS: [
        `This feature is still in development.`,
        `${padStringToLength79(`STATS, HP, MP, MV, STR, DEX, CON, INT, WIS, SPIRIT`)}`,
        `<span style="color:var(--red)">Health Points (HP):</span> show how much damage can be taken before death`,
        `<span style="color:var(--red)">Magic Points (MP):</span> are spent to cast spells`,
        `<span style="color:var(--red)">Move Points (MV):</span> are spent moving between rooms`,
        `HP, MP, & MV slowly recover on their own, and can be replenished in other ways.`,
        `<span style="color:var(--red)">Strength (STR):</span> affects melee combat damage, skill success, inventory capacity`,
        `<span style="color:var(--red)">Dexterity (DEX):</span> affects melee combat damage, skill success, dodging`,
        `<span style="color:var(--red)">Constitution (CON):</span> affects max HP, resistance, regeneration`,
        `<span style="color:var(--red)">Intelligence (INT):</span> affects max MP and damage, duration, and mage spells`,
        `<span style="color:var(--red)">Wisdom (WIS):</span> affects max MP and healing, duration, and cleric spells `,
        `<span style="color:var(--red)">Spirit:</span> shows alignment of spirit to the sun or moon, affecting many spells and effects. Negative spirit scores are aligned to the moon, and positive scores to the sun; a score of 0 is perfectly neutral. Spirit will move away from the alignment of defeated foes (e.g. become more moon-aligned by defeating sun-aligned foes).`,
    ],
    SUGGEST: [
        `${padStringToLength79(`SUGGEST`)}`,
        `Leave a suggestion for an author who has chosen you as their EDITOR. A quality suggestion is specific, encouraging, and as brief as possible.`,
    ],
    SUGGESTIONS: [
        `${padStringToLength79(`SUGGESTIONS`)}`,
        `View a list of suggestions left by your EDITOR in the unpublished zone you're in. Mark a suggestion <span style="color:var(--green_light)">completed</span> to show you have made the change. If you don't agree with a suggestion, you can mark it <span style="color:var(--red)">declined</span> without making the change.`,
    ],
    TELEPATH: [
        `${padStringToLength79(`TELEPATH`)}`,
        `Communicate with a single user from anywhere e.g. "TELEPATH Ralu Hello, how are you?"`,
    ],
    UNIQUE_MOB: [
        `This feature is still in development.`,
        `${padStringToLength79(`Unique Mob`)}`,
        `A Unique mob can only exist in one place at one time. It is different from a mob like "a goblin", where there could be any number of them in a zone or in the world. Use this for special mobs with an identity, especially those with a name (e.g. Greg, the Blacksmith), where it wouldn't make sense for there to be more than one in the world.`,
    ],
    UPDATES: [
        `View of list of recent updates (bug fixes, etc.) made to Restoria. Include a number (UPDATES 5) to limit how many are shown, or UPDATE ALL to see everything.`,
    ],
    WEAPON_PROPERTIES: [
        `This feature is still in development.`,
        `${padStringToLength79(`Weapon Properties`)}`,
        `Users and Mobs can WIELD a weapon to equip it for combat.`,
        `<span style="color:var(--red)">Damage:</span>The first number determines how many dice are rolled. The second is how many sides per die (ie the max roll per die). e.g. 3d4 Bludgeoning deals between 3-12 bludgeoning damage per hit.`,
        `<span style="color:var(--red)">Finesse:</span> uses dexterity to determine damage bonus (instead of strength)`,
        `<span style="color:var(--red)">Light:</span> can be thrown or dualwielded`,
        `<span style="color:var(--red)">Reach:</span> can hit from middle or front row of formation`,
        `<span style="color:var(--red)">Ranged:</span> can hit from any row of formation`,
        `<span style="color:var(--red)">TwoHand:</span> takes up both hands, and in exchange it usually does more damage and has more effective affixes`,
    ],
    WHO: [
        `This feature is still in development.`,
        `${padStringToLength79(`WHO`)}`,
        `Typing WHO shows you all the authors currently logged into Restoria, with some basic info about each. You can contact these users using TELEPATH.`,
    ],
};
export default HELP;
