// HELP
// Arrays of help messages for the HELP command
const HELP = {
    AFFIX: [`AFFIX`, `This feature is still in development.`],
    AGGRESSIVE_MOB: [
        `AGGRESSIVE_MOB`,
        `This feature is still in development. When implemented, An aggressive mob will attack users without being provoked.`,
    ],
    CHEATSHEET: [
        `Common Commands in Restoria - Type HELP CHEATSHEET in-game to see this again.`,
        `<span style="color:var(--red)">NORTH</span>, <span style="color:var(--red)">EAST</span>, <span style="color:var(--red)">SOUTH</span>, <span style="color:var(--red)">WEST</span>, <span style="color:var(--red)">UP</span>, <span style="color:var(--red)">DOWN</span>: move one room in any direction`,
        `<span style="color:var(--red)">LOOK: see what (and who) is in the room with you</span>`,
        `<span style="color:var(--red)">RECALL: warp back to "The Snails", the center of Restoria Town</span>`,
        `<span style="color:var(--red)">CREATE: start with CREATE ZONE to write things into the game</span>`,
        `<span style="color:var(--red)">GOTO: warp to any room in any zone you create or edit</span>`,
        `<span style="color:var(--red)">EDIT: make changes to an item, mob, room, etc. you've created</span>`,
        `<span style="color:var(--red)">ERASE: remove something you've created from the game</span>`,
        `<span style="color:var(--red)">EDITOR:</span> choose another user to make suggestions in your zones`,
        `<span style="color:var(--red)">SUGGEST:</span> leave a suggestion for an author to improve something`,
        `<span style="color:var(--red)">SUGGESTIONS: view suggestions from your editor in your zone</span>`,
        `<span style="color:var(--red)">SAY: send a message to users in the same room</span>`,
        `<span style="color:var(--red)">SHOUT: send a message to users in the same room</span>`,
        `<span style="color:var(--red)">TELEPATH: send a message to a single user</span>`,
        `<span style="color:var(--red)">RULES: read and follow these if you want to stay in Restoria</span>`,
    ],
    CONTAINER: [
        `CONTAINER, CAPACITY`,
        `A container is an item that can hold other (non-container) items inside. A container's capacity is the maximum items it can store (10, by default).`,
    ],
    CREATE: [
        `CREATE`,
        `You are an author in Restoria, and authors can CREATE ZONE, CREATE ITEM, CREATE MOB, CREATE ROOM, and CREATE EXIT to add things to zones they own. Each option opens a form to enter your writing, and the HELP for each form will display automatically with the form.`,
    ],
    CREATE_EXIT: [
        `================================ Create Exit =================================`,
        `Open an exit between this room and an adjacent room.`,
        `If there's no available room in a direction, it won't appear on the form.`,
        `If the "Direction" dropdown is empty, try CREATE ROOM instead.`,
    ],
    CREATE_ITEM: [
        `=============================== Create Item ==================================`,
        `<span style="color:var(--red)">Name:</span> e.g '<span style="color: var(--blue_light)">a green potion</span>' or '<span style="color: var(--blue_light)">Excaliburr the Frozen'</span>`,
        `<span style="color:var(--red)">Keywords:</span> e.g 'potion, green' or 'sword, Excaliburr, Frozen`,
        `<span style="color:var(--red)">Type:</span> Each has its special features, except 'none'.`,
        `<span style="color:var(--red)">MinLvl:</span> A player must be at least this level to use or equip it.`,
        `<span style="color:var(--red)">Price:</span> The item costs this much to purchase (selling price will be less).`,
        `<span style="color:var(--red)">Container:</span> This item can spawn or hold other items inside.`,
        `<span style="color:var(--red)">Look:</span> This is how the player sees the item when they look or enter a room.`,
        `<span style="color:var(--red)">Examine:</span> The player sees this paragraph when they examine the item.`,
    ],
    CREATE_MOB: [
        `================================ Create Mob ==================================`,
        `<span style="color:var(--red)">Name:</span> e.g '<span style="color: var(--green_light)">a green goblin</span>' or '<span style="color: var(--green_light)">Greg the blacksmith'</span>`,
        `<span style="color:var(--red)">Keywords:</span> e.g 'goblin, green' or 'blacksmith, Greg'`,
        `<span style="color:var(--red)">Pronouns:</span> Pronouns may appear in place of a name ("Greg eats." vs "<u>He</u> eats.").`,
        `<span style="color:var(--red)">Level:</span> A mob's level determines its stats, and what spells and abilities it has learned.`,
        `<span style="color:var(--red)">Job:</span> A job determines abilities and combat style.`,
        `<span style="color:var(--red)">Look:</span> This is how the player sees the mob when they look or enter a room.`,
        `<span style="color:var(--red)">Examine:</span> The player sees this paragraph when they examine the mob.`,
    ],
    CREATE_ROOM: [
        `================================ Create Room =================================`,
        `<span style="color:var(--red)">Name:</span> e.g '<span style="color: var(--yellow_light)">A Long Hallway</span>' or '<span style="color: var(--yellow_light)">The Potion Shoppe'</span>`,
        `<span style="color:var(--red)">Direction:</span> This is the location of the new room, from here.`,
        `<span style="color:var(--red)">Dark:</span> Items, mobs, and players are hidden unless a lamp is in the room.`,
        `<span style="color:var(--red)">Indoors:</span> Weather won't take effect here.`,
        `<span style="color:var(--red)">On Water:</span> Players and mobs can't enter without levitate.`,
        `<span style="color:var(--red)">Underwater:</span> Players will take drowning damage without magic.`,
        `<span style="color:var(--red)">Examine:</span> This is how the player sees the room when they look or enter it.`,
    ],
    CREATE_USER: [
        `================================ Create User =================================`,
        `<span style="color:var(--red)">Name:</span> Must be letters only (max. 18), no unique irl names (e.g. no "Obama")</span>.`,
        `<span style="color:var(--red)">Password:</span> Has min. 8 characters, including uppercase, lowercase, <u>and</u> number.`,
        `<span style="color:var(--red)">Pronouns:</span> Pronouns may appear in place of a name ("Greg eats." vs "<u>He</u> eats.").`,
        `<span style="color:var(--red)">Job:</span> This determines abilities, spells, and fighting style in combat.`,
    ],
    CREATE_ZONE: [
        `================================ Create Zone =================================`,
        `<span style="color:var(--red)">Name:</span> This is the zone's title, e.g. "The Mushroom City"</span>`,
        `<span style="color:var(--red)">Respawn:</span> This is how many minutes before the whole zone's mobs, doors, & items respawn.`,
        `<span style="color:var(--red)">Look:</span> The player sees this sentence when they survey the wilderness nearby.`,
        `  e.g. "Clouds of spores and odd, fungal shapes protrude from the horizon."`,
        `<span style="color:var(--red)">Examine:</span> The player sees this paragraph when they examine the zone.`,
        `<span style="color:var(--red)">Study:</span> The player learns some history when they study the zone.`,
        `<span style="color:var(--red)">Research:</span> These paragraphs tell the full history of the zone.`,
        `  A good research text rewards the reader with some secrets about the zone.`,
    ],
    DESCRIPTION: [`DESCRIPTION, LOOK, EXAMINE, STUDY, RESEARCH`],
    EDIT: [`EDIT`],
    EDIT_ITEM: [`EDIT_ITEM`],
    EDIT_MOB: [`EDIT_MOB`],
    EDIT_ROOM: [`EDIT_ROOM`],
    EDIT_USER: [`EDIT_USER`],
    EDIT_ZONE: [`EDIT_ZONE`],
    EDITOR: [`EDITOR`],
    ERASE: [`ERASE, DELETE`],
    ERASE_EXIT: [
        `================================ Erase Exit =================================`,
        `Remove an exit between this room and an adjacent room.`,
        `Erasing an exit can make some rooms in your zone inaccessible.`,
        `You can use GOTO, then CREATE EXIT or CREATE ROOM to reconnect them.`,
    ],
    ERASE_ITEM: [`ERASE_ITEM`],
    ERASE_MOB: [`ERASE_MOB`],
    ERASE_ROOM: [`ERASE_ROOM`],
    ERASE_USER: [`ERASE_USER`],
    ERASE_ZONE: [`ERASE_ZONE`],
    EXITS: [`EXITS`],
    FINESSE_WEAPON: [`FINESSE_WEAPON`],
    GOTO: [`GOTO`],
    HIDDEN: [`HIDDEN_ITEM, HIDDEN_USER, HIDDEN_MOB, HIDDEN_EXIT`],
    ITEM_NODE: [`ITEM_NODE`],
    ITEM_TYPE: [
        `ITEM_TYPE, ARMOR, POTION, SCROLL, TOKEN, TREASURE, WAND, WEAPON, FISHING_ROD`,
    ],
    ITEM_TAG: [`ITEM_TAG, FIXTURE, FOOD, LAMP, TEMPORARY`],
    JOB: [`JOB`],
    KEYWORDS: [`KEYWORDS`],
    LIGHT_WEAPON: [`LIGHT_WEAPON`],
    MOB: [`MOB, MONSTER, NPC`],
    MOB_NODE: [`MOB_NODE`],
    MOUNT: [`MOUNT`],
    MOVE: [`MOVE`],
    NAME: [`NAME`],
    PASSWORD: [`PASSWORD`],
    PRONOUNS: [`PRONOUNS`],
    QUIT: [`QUIT`],
    RANGED_WEAPON: [`RANGED_WEAPON`],
    REACH_WEAPON: [`REACH_WEAPON`],
    RECALL: [`RECALL`],
    SAY: [`SAY`],
    SHOUT: [`SHOUT`],
    SPELL: [`SPELL`],
    STATS: [`STATS, HP, MP, MV, STR, DEX, CON, INT, WIS, SPIRIT`],
    SUGGEST: [`SUGGEST`],
    SUGGESTIONS: [`SUGGESTIONS`],
    TELEPATH: [`TELEPATH`],
    TWO_HAND_WEAPON: [`TWO_HAND_WEAPON`],
    UNIQUE_MOB: [`UNIQUE_MOB`],
    WHO: [`WHO`],
};
export default HELP;
