// HELP

import padStringToLength80 from "../util/padStringToLength80.js";

// Arrays of help messages for the HELP command
const HELP = {
  AFFIX: [
    `${padStringToLength80(`Affix`)}`,
    `This feature is still in development.`,
    `${padStringToLength80(`Item Affix`, `-`)}`,
    `An affix boosts a player's stat while the item is equipped.`,
    `The effects of each stat is explained in a help file (e.g. HELP DEXTERITY)`,
    `An item can have up to 3 affixes, and it's okay for some items to have none. `,
    `It's okay to have more than one affix on the same stat,`,
    `e.g. for a double or triple boost to dexterity on the same boots.`,
  ],
  AGGRESSIVE_MOB: [
    `${padStringToLength80(`Aggressive Mob`)}`,
    `This feature is still in development. When implemented, An aggressive mob will attack users without being provoked.`,
  ],
  ARMOR: [
    `${padStringToLength80(`Armor`)}`,
    `An armor item may fit on one location, or have multiple options.`,
    `(e.g. a long, golden chain might fit around the neck or around the waist)`,
  ],
  CHEATSHEET: [
    `${padStringToLength80(`HELP CHEATSHEET`)}`,
    `${padStringToLength80(
      `Common Commands in Restoria: Type HELP CHEATSHEET in-game to see this again.`,
      ` `
    )}`,
    `<span style="color:var(--red)">NORTH</span>, <span style="color:var(--red)">EAST</span>, <span style="color:var(--red)">SOUTH</span>, <span style="color:var(--red)">WEST</span>, <span style="color:var(--red)">UP</span>, <span style="color:var(--red)">DOWN</span>: move one room in any direction`,
    `<span style="color:var(--red)">LOOK: see what (and who) is in the room with you</span>`,
    `<span style="color:var(--red)">RECALL: warp back to "The Snails", the center of Restoria Town</span>`,
    `<span style="color:var(--red)">CREATE: start with CREATE ZONE to write things into the game</span>`,
    `<span style="color:var(--red)">GOTO: warp to any room in any zone you create or edit</span>`,
    `<span style="color:var(--red)">EDIT: make changes to an item, mob, room, etc. you've created</span>`,
    `<span style="color:var(--red)">ERASE: remove something you've created from the game</span>`,
    `<span style="color:var(--red)">EDITOR:</span> choose another user to make suggestions in your zones`,
    `<span style="color:var(--red)">SUGGEST:</span> leave a suggestion for an author to improve something`,
    `<span style="color:var(--red)">SUGGESTIONS: view suggestions from your editor in your zone</span>`,
    `<span style="color:var(--red)">SAY: send a message to users in the same room</span>`,
    `<span style="color:var(--red)">SHOUT: send a message to users in the same room</span>`,
    `<span style="color:var(--red)">TELEPATH: send a message to a single user</span>`,
    `<span style="color:var(--red)">RULES: read and follow these if you want to stay in Restoria</span>`,
  ],
  CONTAINER: [
    `${padStringToLength80(`CONTAINER, CAPACITY`)}`,
    `A container is an item that can hold other (non-container) items inside. A container's capacity is the maximum items it can store (10, by default).`,
  ],
  CREATE: [
    `${padStringToLength80(`CREATE`)}`,
    `You are an author in Restoria, and authors can CREATE ZONE, CREATE ITEM, CREATE MOB, CREATE ROOM, and CREATE EXIT to add things to zones they own. Each option opens a form to enter your writing, and the HELP for each form will display automatically when it opens.`,
  ],
  CREATE_EXIT: [
    `${padStringToLength80(`CREATE EXIT`)}`,
    `Open an exit between this room and an adjacent room.`,
    `If there's no available room in a direction, it won't appear on the form.`,
    `If the "Direction" dropdown is empty, try CREATE ROOM instead.`,
  ],
  CREATE_ITEM: [
    `${padStringToLength80(`CREATE ITEM`)}`,
    `<span style="color:var(--red)">Name:</span> e.g '<span style="color: var(--blue_light)">a green potion</span>' or '<span style="color: var(--blue_light)">Excaliburr the Frozen'</span>`,
    `<span style="color:var(--red)">Keywords:</span> e.g 'potion, green' or 'sword, Excaliburr, Frozen`,
    `<span style="color:var(--red)">Type:</span> Each has its special features, except 'none'.`,
    `<span style="color:var(--red)">MinLvl:</span> A player must be at least this level to use or equip it.`,
    `<span style="color:var(--red)">Price:</span> The item costs this much to purchase (selling price will be less).`,
    `<span style="color:var(--red)">Container:</span> This item can spawn or hold other items inside.`,
    `<span style="color:var(--red)">Look:</span> This is how the player sees the item when they look or enter a room.`,
    `<span style="color:var(--red)">Examine:</span> The player sees this paragraph when they examine the item.`,
  ],
  CREATE_MOB: [
    `${padStringToLength80(`CREATE MOB`)}`,
    `<span style="color:var(--red)">Name:</span> e.g '<span style="color: var(--green_light)">a green goblin</span>' or '<span style="color: var(--green_light)">Greg the blacksmith'</span>`,
    `<span style="color:var(--red)">Keywords:</span> e.g 'goblin, green' or 'blacksmith, Greg'`,
    `<span style="color:var(--red)">Pronouns:</span> Pronouns may appear in place of a name ("Greg eats." vs "<u>He</u> eats.").`,
    `<span style="color:var(--red)">Level:</span> A mob's level determines its stats, and what spells and abilities it has learned.`,
    `<span style="color:var(--red)">Job:</span> A job determines abilities and combat style.`,
    `<span style="color:var(--red)">Look:</span> This is how the player sees the mob when they look or enter a room.`,
    `<span style="color:var(--red)">Examine:</span> The player sees this paragraph when they examine the mob.`,
  ],
  CREATE_ROOM: [
    `${padStringToLength80(`CREATE ROOM`)}`,
    `<span style="color:var(--red)">Name:</span> e.g '<span style="color: var(--yellow_light)">A Long Hallway</span>' or '<span style="color: var(--yellow_light)">The Potion Shoppe'</span>`,
    `<span style="color:var(--red)">Direction:</span> This is the location of the new room, from here.`,
    `<span style="color:var(--red)">Dark:</span> Items, mobs, and players are hidden unless a lamp is in the room.`,
    `<span style="color:var(--red)">Indoors:</span> Weather won't take effect here.`,
    `<span style="color:var(--red)">On Water:</span> Players and mobs can't enter without levitate.`,
    `<span style="color:var(--red)">Underwater:</span> Players will take drowning damage without magic.`,
    `<span style="color:var(--red)">Examine:</span> This is how the player sees the room when they look or enter it.`,
  ],
  CREATE_USER: [
    `${padStringToLength80(`CREATE USER`)}`,
    `This command is currently disabled during Beta testing.`,
    `<span style="color:var(--red)">Name:</span> Must be letters only (max. 18), no unique irl names (e.g. no "Obama")</span>.`,
    `<span style="color:var(--red)">Password:</span> Has min. 8 characters, including uppercase, lowercase, <u>and</u> number.`,
    `<span style="color:var(--red)">Pronouns:</span> Pronouns may appear in place of a name ("Greg eats." vs "<u>He</u> eats.").`,
    `<span style="color:var(--red)">Job:</span> This determines abilities, spells, and fighting style in combat.`,
  ],
  CREATE_ZONE: [
    `${padStringToLength80(`CREATE ZONE`)}`,
    `<span style="color:var(--red)">Name:</span> This is the zone's title, e.g. "The Mushroom City"</span>`,
    `<span style="color:var(--red)">Respawn:</span> This is how many minutes before the whole zone's mobs, doors, & items respawn.`,
    `<span style="color:var(--red)">Look:</span> The player sees this sentence when they survey the wilderness nearby.`,
    `  e.g. "Clouds of spores and odd, fungal shapes protrude from the horizon."`,
    `<span style="color:var(--red)">Examine:</span> The player sees this paragraph when they examine the zone.`,
    `<span style="color:var(--red)">Study:</span> The player learns some history when they study the zone.`,
    `<span style="color:var(--red)">Research:</span> These paragraphs tell the full history of the zone.`,
    `  A good research text rewards the reader with some secrets about the zone.`,
  ],
  DESCRIPTION: [
    `${padStringToLength80(`DESCRIPTION, LOOK, EXAMINE, STUDY, RESEARCH`)}`,
    `<span style="color:var(--red)">Look:</span> A 'LOOK' description should fit on one line (80 characters or less). It is a full sentence, and a reader's first impression of the item, mob, user, or zone it describes. The 'look' descriptions of every item, mob, and user in a room are shown automatically to a player when they enter that room, and when they use the LOOK command on its own.`,
    `<span style="color:var(--red)">Examine:</span> When a reader uses the EXAMINE command on an item, mob, or user, this short paragraph (240 characters or less) is what they see. A user also automatically sees a room's 'examine' description when they enter it, and when they use the LOOK command on its own.`,
    `<span style="color:var(--red)">Study:</span> When a reader uses the STUDY command on an item, mob, user, room, or zone, this long description (640 characters or less) is what they see. It should include rich detail that a reader wouldn't notice at first glance, and may even share secrets to reward those careful and patient readers who take the time to study.`,
    `<span style="color:var(--red)">Research:</span> When a reader uses the RESEARCH command on an item, mob, user, room, or zone, this complete story (1600 characters or less) is shown to them. Good authors will use the 'research' description to tell some history. They may explain why certain things in their zone are they way they are. This is also a fun place to include easter eggs or major secrets about your zone, since only the best and most deserving readers explore with the RESEARCH command.`,
  ],
  EDIT: [
    `${padStringToLength80(`EDIT`)},`,
    `After creating a zone, item, mob, room, or user in Restoria, you can use EDIT to change or add more details. EDIT ITEM, EDIT MOB, and EDIT ROOM allow many options for customization, while EDIT USER and EDIT ZONE allow only basic description changes, for now. Each option opens a form to change its target, and the HELP for each form will display automatically when it opens.`,
  ],
  EDIT_ITEM: [
    `${padStringToLength80(`EDIT ITEM`)},`,
    `<span style="color:var(--red)">Name:</span> e.g '<span style="color: var(--blue_light)">a green potion</span>' or '<span style="color: var(--blue_light)">Excaliburr the Frozen'</span>`,
    `<span style="color:var(--red)">Keywords:</span> e.g 'potion, green' or 'sword, Excaliburr, Frozen`,
    `<span style="color:var(--red)">Price:</span> The item costs this much to purchase (selling price will be less).`,
    `<span style="color:var(--red)">MinLvl:</span> A player must be at least this level to use or equip it.`,
    `<span style="color:var(--red)">Type:</span> Each has its special features, except 'none'.`,
  ],
  EDIT_MOB: [`EDIT_MOB`],
  EDIT_ROOM: [`EDIT_ROOM`],
  EDIT_USER: [`EDIT_USER`],
  EDIT_ZONE: [`EDIT_ZONE`],
  EDITOR: [`EDITOR`],
  ERASE: [`ERASE, DELETE`],
  ERASE_EXIT: [
    `${padStringToLength80(`ERASE EXIT`)},`,
    `Remove an exit between this room and an adjacent room.`,
    `Erasing an exit can make some rooms in your zone inaccessible.`,
    `You can use GOTO, then CREATE EXIT or CREATE ROOM to reconnect them.`,
  ],
  ERASE_ITEM: [`ERASE_ITEM`],
  ERASE_MOB: [`ERASE_MOB`],
  ERASE_ROOM: [`ERASE_ROOM`],
  ERASE_USER: [`ERASE_USER`],
  ERASE_ZONE: [`ERASE_ZONE`],
  EXITS: [`EXITS`],
  FINESSE_WEAPON: [`This feature is still in development.`, `FINESSE_WEAPON`],
  GOTO: [`GOTO`],
  HIDDEN: [
    `This feature is still in development.`,
    `HIDDEN_ITEM, HIDDEN_USER, HIDDEN_MOB, HIDDEN_EXIT`,
  ],
  ITEM_NODE: [
    `${padStringToLength80(`Item Node`)},`,
    `<span style="color:var(--red)">Capacity:</span> how many items can fit inside`,
    `An item node spawns that item into the container when the container is spawned.`,
    `Choose an item and click <span style="color:var(--green)">add</span> to create an item node for it.`,
    `Click <span style="color:var(--red)">remove</span> next to an existing node to remove it.`,
    `These changes won't be saved until you click "Update Item".`,
  ],
  ITEM_SPELL_PROPERTIES: [
    `${padStringToLength80(`Item Spell Properties`)},`,
    `Each spell has a help file describing its effects (e.g. HELP BLESS)`,
    `<span style="color:var(--red)">Level:</span> higher can mean stronger effect, more damage, longer duration, etc.`,
    `<span style="color:var(--red)">Charges:</span> how many times the item can be used before it disappears`,
  ],
  ITEM_TYPE: [
    `ITEM_TYPE, ARMOR, POTION, SCROLL, TOKEN, TREASURE, WAND, WEAPON, FISHING_ROD`,
  ],
  ITEM_TAG: [
    `${padStringToLength80(`Item Tags, Fixture, Food, Lamp, Temporary`)},`,
    `<span style="color:var(--red)">Cleric:</span> Clerics can use or equip it.`,
    `<span style="color:var(--red)">Mage:</span> Mages can use or equip it.`,
    `<span style="color:var(--red)">Rogue:</span> Rogues can use or equip it.`,
    `<span style="color:var(--red)">Warrior:</span> Warriors can use or equip it.`,
    `<span style="color:var(--red)">Dark:</span> Dark aura players can use or equip it.`,
    `<span style="color:var(--red)">Neutral:</span> Neutral aura players can use or equip it.`,
    `<span style="color:var(--red)">Light:</span> Light aura players can use or equip it.`,
    `<span style="color:var(--red)">Food:</span> It can be eaten and may hold a spell.`,
    `<span style="color:var(--red)">Lamp:</span> It lights up a dark room, showing players, mobs, and items.`,
    `<span style="color:var(--red)">Hidden:</span> It's not visible until you search.`,
    `<span style="color:var(--red)">Fixture:</span> The object cannot be taken or moved (e.g. a large wardrobe).`,
    `<span style="color:var(--red)">Quest:</span> It is needed for a quest.`,
    `<span style="color:var(--red)">Temporary:</span> The item is erased from inventory when you log out.`,
    `<span style="color:var(--red)">Container:</span> This item can spawn or hold other items inside.`,
  ],
  JOB: [`This feature is still in development.`, `JOB`],
  KEYWORDS: [`KEYWORDS`],
  LIGHT_WEAPON: [`This feature is still in development.`, `LIGHT_WEAPON`],
  MOB: [`MOB, MONSTER, NPC`],
  MOB_NODE: [`MOB_NODE`],
  MOUNT: [`This feature is still in development.`, `MOUNT`],
  MOVE: [`MOVE`],
  NAME: [`NAME`],
  PASSWORD: [`This feature is still in development.`, `PASSWORD`],
  PRONOUNS: [`PRONOUNS`],
  QUIT: [`QUIT`],
  RANGED_WEAPON: [`This feature is still in development.`, `RANGED_WEAPON`],
  REACH_WEAPON: [`This feature is still in development.`, `REACH_WEAPON`],
  RECALL: [`RECALL`],
  SAY: [`SAY`],
  SHOUT: [`SHOUT`],
  SPELL: [`This feature is still in development.`, `SPELL`],
  STATS: [
    `This feature is still in development.`,
    `STATS, HP, MP, MV, STR, DEX, CON, INT, WIS, SPIRIT`,
  ],
  SUGGEST: [`SUGGEST`],
  SUGGESTIONS: [`SUGGESTIONS`],
  TELEPATH: [`TELEPATH`],
  TWO_HAND_WEAPON: [`This feature is still in development.`, `TWO_HAND_WEAPON`],
  UNIQUE_MOB: [`This feature is still in development.`, `UNIQUE_MOB`],
  WEAPON: [
    `This feature is still in development.`,
    `${padStringToLength80(`Weapon Properties`)},`,
    `<span style="color:var(--red)">Damage:</span>The first number determines how many dice are rolled.`,
    `  The second is how many sides per die (ie the max roll per die).`,
    `  e.g. 3d4 Bludgeoning deals between 3-12 bludgeoning damage per hit.`,
    `<span style="color:var(--red)">Finesse:</span> uses dexterity to determine damage bonus`,
    `<span style="color:var(--red)">Light:</span> can be thrown or wielded in off-hand`,
    `<span style="color:var(--red)">Reach:</span> can hit from middle row of formation`,
    `<span style="color:var(--red)">Ranged:</span> can hit from back row of formation`,
    `<span style="color:var(--red)">Twohand:</span> can't be paired with a shield or off-hand`,
  ],
  WHO: [`WHO`],
};

export default HELP;
