const SKILL = {
    NONE: "none",
    AMBUSH: "ambush",
    BACKSTAB: "backstab",
    CLEAVE: "cleave",
    DEFEND: "defend",
    DISARM: "disarm",
    DODGE: "dodge",
    GUARD: "guard",
    HIDE: "hide",
    KICK: "kick",
    MEDITATE: "meditate",
    DUALWIELD: "dualwield",
    PARRY: "parry",
    PICK: "pick",
    SCAN: "scan",
    SECOND_ATTACK: "second attack",
    SHOVE: "shove",
    SNEAK: "sneak",
    STEAL: "steal",
    THIRD_ATTACK: "third attack",
    THROW: "throw",
    TRACK: "track",
    TRAP: "trap",
    TRIP: "trip",
};
export const skills = Object.values(SKILL);
export default SKILL;
