const SPELL = {
  NONE: "none",
  ARCANE_EYE: "arcane eye",
  ATTUNE: "attune",
  BERSERK: "berserk",
  BLESS: "bless",
  BLIND: "blind",
  BLINK: "blink",
  BLIZZARD: "blizzard",
  BLOOD_MAGIC: "blood magic",
  BREADCRUMBS: "breadcrumbs",
  BREATHE_WATER: "breathe water",
  BUBBLE: "bubble",
  CHARM: "charm",
  COLD: "cold",
  COLOR_SPRAY: "color spray",
  CONJURE_ELEMENTAL: "conjure elemental",
  CREATE_FOOD: "create food",
  CREATE_WATER: "create water",
  CURE_BLIND: "cure blind",
  CURE_FATIGUE: "cure fatigue",
  CURE_POISON: "cure poison",
  CURSE: "curse",
  DIMENSION_DOOR: "dimension door",
  DISCERN_SPIRIT: "discern spirit",
  DISINTEGRATE: "disintegrate",
  DISPEL_MAGIC: "dispel magic",
  DRAIN: "drain",
  ECHO_SPIRIT: "echo spirit",
  FAERIE_FIRE: "faerie fire",
  FARSIGHT: "farsight",
  FATIGUE: "fatigue",
  FEAR: "fear",
  FIRE: "fire",
  FIRESTORM: "firestorm",
  GATE: "gate",
  HARM: "harm",
  HEAL: "heal",
  IDENTIFY: "identify",
  INFRAVISION: "infravision",
  INVISIBILITY: "invisibility",
  LEVITATE: "levitate",
  LIFT_CURSE: "lift curse",
  LIGHTNING: "lightning",
  LOCATE_OBJECT: "locate object",
  MAGIC_MISSILE: "magic missile",
  MANASHIELD: "manashield",
  MASS_INVISIBILITY: "mass invisibility",
  MASS_LEVITATE: "mass levitate",
  MASS_REFRESH: "mass refresh",
  MINOR_CREATION: "minor creation",
  MIRAGE: "mirage",
  MIRROR_IMAGES: "mirror images",
  ONE_HEART: "one heart",
  POISON: "poison",
  PROTECT: "protect",
  REFRESH: "refresh",
  RESIST_COLD: "resist cold",
  RESIST_ELECTRIC: "resist electric",
  RESIST_FIRE: "resist fire",
  RESURRECT: "resurrect",
  ROT: "rot",
  SCRY: "scry",
  SEE_INVISIBLE: "see invisible",
  SENSE_LIFE: "sense life",
  SENSE_PRESENCE: "sense presence",
  SHIELD: "shield",
  SLEEP: "sleep",
  SPIRIT_ARMOR: "spirit armor",
  SPIRIT_BOLT: "spirit bolt",
  SPIRIT_SHOCK: "spirit shock",
  STONE_SKIN: "stone skin",
  STRENGTH: "strength",
  SUMMON: "summon",
  TELEPORT: "teleport",
  THORNS: "thorns",
  TREMOR: "tremor",
  VISIT: "visit",
  WEAKEN: "weaken",
  WORD_OF_RECALL: "word of recall",
};

export const spells = Object.values(SPELL);

export default SPELL;
