const SPELL = {
  AMBUSH: 'ambush',
  ARCANE_EYE: 'arcane eye',
  ATTUNE: 'attune',
  BACKSTAB: 'backstab',
  BERSERK: 'berserk',
  BLESS: 'bless',
  BLIND: 'blind',
  BLINK: 'blink',
  BLIZZARD: 'blizzard',
  BLOOD_MAGIC: 'blood magic',
  BREADCRUMBS: 'breadcrumbs',
  BREATHE_WATER: 'breathe water',
  BUBBLE: 'bubble',
  CHARM: 'charm',
  CLEAVE: 'cleave',
  COLD: 'cold',
  COLOR_SPRAY: 'color spray',
  CONJURE_ELEMENTAL: 'conjure elemental',
  CREATE_FOOD: 'create food',
  CREATE_WATER: 'create water',
  CURE_BLIND: 'cure blind',
  CURE_FATIGUE: 'cure fatigue',
  CURE_POISON: 'cure poison',
  CURSE: 'curse',
  DEFEND: 'defend',
  DIMENSION_DOOR: 'dimension door',
  DISARM: 'disarm',
  DISCERN_SPIRIT: 'discern spirit',
  DISINTEGRATE: 'disintegrate',
  DISPEL_MAGIC: 'dispel magic',
  DRAIN: 'drain',
  ECHO_SPIRIT: 'echo spirit',
  FAERIE_FIRE: 'faerie fire',
  FARSIGHT: 'farsight',
  FATIGUE: 'fatigue',
  FEAR: 'fear',
  FIRE: 'fire',
  FIRESTORM: 'firestorm',
  GATE: 'gate',
  HARM: 'harm',
  HEAL: 'heal',
  HIDE: 'hide',
  IDENTIFY: 'identify',
  INFRAVISION: 'infravision',
  INVISIBILITY: 'invisibility',
  KICK: 'kick',
  LEVITATE: 'levitate',
  LIFT_CURSE: 'lift curse',
  LIGHTNING: 'lightning',
  LOCATE_OBJECT: 'locate object',
  MAGIC_MISSILE: 'magic missile',
  MALEDICTION: 'malediction',
  MANASHIELD: 'manashield',
  MASS_INVISIBILITY: 'mass invisibility',
  MASS_LEVITATE: 'mass levitate',
  MASS_REFRESH: 'mass refresh',
  MEDITATE: 'meditate',
  MINOR_CREATION: 'minor creation',
  MIRAGE: 'mirage',
  MIRROR_IMAGES: 'mirror images',
  ONE_HEART: 'one heart',
  PICK: 'pick',
  POISON: 'poison',
  PROTECT: 'protect',
  REFRESH: 'refresh',
  RESIST_COLD: 'resist cold',
  RESIST_ELECTRIC: 'resist electric',
  RESIST_FIRE: 'resist fire',
  RESURRECT: 'resurrect',
  ROT: 'rot',
  SCAN: 'scan',
  SCRY: 'scry',
  SEE_INVISIBLE: 'see invisible',
  SENSE_LIFE: 'sense life',
  SENSE_PRESENCE: 'sense presence',
  SHIELD: 'shield',
  SHOVE: 'shove',
  SLEEP: 'sleep',
  SNEAK: 'sneak',
  SPIRIT_ARMOR: 'spirit armor',
  SPIRIT_BOLT: 'spirit bolt',
  SPIRIT_SHOCK: 'spirit shock',
  STEAL: 'steal',
  STONE_SKIN: 'stone skin',
  STRENGTH: 'strength',
  SUMMON: 'summon',
  TELEPORT: 'teleport',
  THORNS: 'thorns',
  THROW: 'throw',
  TRACK: 'track',
  TRAP: 'trap',
  TREMOR: 'tremor',
  TRIP: 'trip',
  VISIT: 'visit',
  WEAKEN: 'weaken',
  WORD_OF_RECALL: 'word of recall',
};

export default SPELL;
