// validCommandWords
// * most commonly used commands are bumped up out of alpha-order to take priority when abbreviated (e.g. we want "d" to mean down, not delete)
export const validCommandWords = [
    "autoexamine",
    "bug",
    "bugs",
    "create",
    "down", // *
    "delete",
    "drop",
    "east",
    "edit",
    "editor",
    // * normally wouldn't include abbrevs here,
    // but the order below is to make sure eq takes priority,
    // but "equip" is not expanded to equipment
    "eq", // *
    "equip", // *
    "equipment", // *
    "equipped",
    "erase",
    "examine",
    "exits",
    "get",
    "give",
    "goto",
    "help",
    "inventory",
    "look",
    "map",
    "north",
    "put", // *
    "plans",
    "password",
    "quit",
    "remove", // *
    "recall",
    "research",
    "roomsummary",
    "south", // *
    "say", // *
    "save",
    "shout",
    "stats",
    "study",
    "suggest", // *
    "suggestions", // *
    "sudobug",
    "sudobugs",
    "telepath",
    "up", // *
    "unequip",
    "updates",
    "west", // *
    "wear",
    "wield",
    "who",
];
export const commandsWith1Param = [
    "abbreviate",
    "affects",
    "afk",
    "ambush",
    "appraise",
    "ask",
    "assist",
    "attack",
    "autoassist",
    "autoexamine",
    "autoflee",
    "backstab",
    "bash",
    "block",
    "brief",
    "bs",
    "close",
    "consider",
    "count",
    "delete",
    "deposit",
    "disarm",
    "donate",
    "drink",
    "drop",
    "eat",
    "edit",
    "editor",
    "enter",
    "exa",
    "examine",
    "fight",
    "follow",
    "guildenroll",
    "guildremove",
    "help",
    "ignore",
    "invite",
    "kick",
    "kill",
    "knock",
    "learn",
    "leader",
    "locate",
    "look",
    "map",
    "mount",
    "offer",
    "open",
    "order",
    "partylock",
    "pick",
    "price",
    "read",
    "recycle",
    "repair",
    "rescue",
    "research",
    "sayto",
    "score",
    "search",
    "sell",
    "setjunk",
    "setparty",
    "setphase",
    "setrescue",
    "setsummon",
    "solo",
    "sort",
    "split",
    "store",
    "study",
    "suggest",
    "target",
    "t",
    "tel",
    "telepath",
    "tell",
    "tell",
    "throw",
    "track",
    "train",
    "trip",
    "unparty",
    "updates",
    "wake",
    "where",
    "whisper",
    "wield",
    "withdraw",
    "zoneinfo",
    "zonelist",
];
export const commandsWith2Params = [
    "buy",
    "cast",
    "compare",
    "create",
    "dub",
    "duel",
    "empty",
    "equip",
    "erase",
    "fill",
    "fly",
    "freeze",
    "get",
    "give",
    "hand",
    "mode",
    "pour",
    "put",
    "reposition",
    "remove",
    "rename",
    "send",
    "steal",
    "take",
    "transfer",
    "unequip",
    "use",
    "wear",
    "wield",
];
export default validCommandWords;
